# - name: nginx config test
#   shell: sudo /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf
#   args:
#     warn: no
#   changed_when: false

- name: redis started
  systemd: name=redis.service state=started

- name: redis reloaded
  systemd: name=redis.service state=restarted
