- file: path=/etc/nginx/ state=directory owner=root group=root mode=0755

- synchronize:
    src: etc/nginx/
    dest: /etc/nginx/
    recursive: yes
    delete: yes
    owner: no
    group: no
    perms: no
