# - name: nginx config test
#   shell: sudo /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf
#   args:
#     warn: no
#   changed_when: false

- name: mysql started
  systemd: name=mysql.service state=started

- name: mysql reloaded
  systemd: name=mysql.service state=restarted

# - name: friction
#   shell: /usr/bin/friction -host=127.0.0.1 -user=root -password=root sys
