# - name: nginx config test
#   shell: sudo /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf
#   args:
#     warn: no
#   changed_when: false

- name: mysql started
  systemd: name=mysql.service state=started

- name: mysql reloaded
  systemd: name=mysql.service state=restarted
