- name: nginx config test
  shell: sudo /usr/local/nginx/sbin/nginx -t -c /etc/nginx/nginx.conf
  args:
    warn: no
  changed_when: false

- name: nginx started
  systemd: name=nginx.service state=started

- name: nginx reloaded
  systemd: name=nginx.service state=reloaded
